#!/bin/sh

if [ "$#" -lt "2" ]
then
  echo "Usage: $0 <pattern> <logfile1 [... logfilen]>" >&2
  exit 1
fi

pattern="$1"

shift

# TODO: support mixed compressed file formats

GREP=grep
FGREP=fgrep

if echo "$1" | grep -q '\.gz$'
then
  GREP=zgrep
  FGREP=zfgrep
elif echo "$1" | grep -q '\.bz2$'
then
  GREP=bzgrep
  FGREP=bzfgrep
fi

ids=$($GREP -i "postfix/.*$pattern" "$@" | sed -e 's/ \+/ /g' | cut -d \  -f 6 | cut -sd : -f 1 | sort | uniq)

test -z "$ids" && exit

# FIXME: This is terribly suboptimal

for id in $ids
do
  if [ "$id" = "NOQUEUE" ]
  then
    $GREP " $id:.*$pattern" "$@" && echo
  else
    $FGREP " $id: " "$@" && echo
  fi
done
